#!/bin/bash

# Define repository info
OWNER="hydrophobis"
REPO="CRun"

# Function to get the latest release from GitHub API
get_latest_release() {
  wget --silent "https://api.github.com/repos/$OWNER/$REPO/releases/latest" | 
  grep '"tag_name":' | 
  sed -E 's/.*"tag_name": "([^"]+)".*/\1/'
}

# Fetch the latest release version
LATEST_VERSION=$(get_latest_release)
echo "Latest version: $LATEST_VERSION"

# Define the download URLs for the AppImage, .deb, and other files
BASE_URL="https://github.com/$OWNER/$REPO/releases/download/$LATEST_VERSION"

PKGBUILD_URL="$BASE_URL/PKGBUILD"

# Function to download a file from GitHub
download_file() {
  URL=$1
  OUTPUT=$2
  echo "Downloading $OUTPUT from $URL..."
  wget -L -o "$OUTPUT" "$URL"
}

# Check if /etc/os-release exists
if [ -f /etc/os-release ]; then
    . /etc/os-release
else
    exit
fi

. /etc/os-release
if [ $NAME != "Arch Linux"]; then
  download_file "$BASE_URL/crun" "crun"
elif [ $NAME == "Arch Linux" ]; then 
  download_file "$PKGBUILD_URL" "PKGBUILD"


if [ -f "crun" ]; then
  sudo cp crun /bin/crun
  rm crun
else
  echo "No executable package found. Assuming PKGBUILD is installed."
  chmod +x PKGBUILD
  ./PKGBUILD
fi

echo "Installation complete"
